config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :articles do
    resources :comments
  end
  resources :users

  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'portfolio' => 'static_pages#portfolio'

  post 'static_pages/thank_you'

  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, User, id: user.id
      can [:create, :update], Article
      can :create, Comment
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :body, presence: true
  validates :title, presence: true
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :article, presence: true
  validates :body, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
    @featured = Article.last
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if request.path != article_path(@article)
      redirect_to @article, status: :moved_permanently
    end
    @comment_count = @article.comments.count
    @comments = @article.comments.order('created_at DESC').paginate(page: params[:page], per_page: 2)
    @featured = Article.last
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :create_date, :create_time, :update_date, :update_time)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment successful.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to @article, alert: 'Comment unsuccessful.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    article = @comment.article
    @comment.destroy
    redirect_to article
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(from: @email,
                            to: ENV['EMAIL_ADDRESS'],
                            subject: "A new contact form message from #{@name}",
                            body: @message).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<article>
  <h2><%= link_to article.title, article %></h2>
  <h6><%= article.create_date.strftime("%d %B %Y") %>, <%= article.create_time.strftime("%l:%M %p %Z") %>
    <% if signed_in? %>
      | <%= link_to 'Edit', edit_article_path(article) %>
      <% if current_user.admin? %>
        | <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </h6>
  <div class="artbody">
    <%= simple_format(article.body) %>
  </div>
</article>

app/views/articles/_comments.html.erb
<div class="comments">
	<% if @article.comments.exists? %>
		<h3><%= @comment_count %> Comments</h3>
		<% @comments.each do |comment| %>
			<hr>
			<h5>
				By <%= comment.user.first_name %> <small><em> <%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
					<% if signed_in? && current_user.admin? %>
						<%= link_to ('<span class="glyphicon glyphicon-remove"></span> Delete').html_safe, article_comment_path(comment.article, comment), class: 'destroy', method: :delete, data: { confirm: 'Are you sure?' } %>
					<% end %>
			</h5>
			<p class="comment-body"><%= comment.body %></p>
		<% end %>
	<% else %>
		<h3>Comments</h3>
		<p>There are no comments yet.<% if signed_in? %> Add yours above now!<% end %></p>
	<% end %>
</div><!-- /comments -->

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :create_date %>
    <%= f.date_select :create_date %>
  </div>

  <div class="field">
    <%= f.label :create_time %>
    <%= f.time_select :create_time %>
  </div>

  <div class="field">
    <%= f.label :update_date %>
    <%= f.date_select :update_date %>
  </div>

  <div class="field">
    <%= f.label :update_time %>
    <%= f.time_select :update_time %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_new_comment.html.erb
<% if signed_in? %>
	<h4>Add a Comment!</h4>
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<div class="form-group">
			<%= f.label :body, "Comments" %>
			<%= f.text_area :body, id: "comment-area" %>
		</div><!-- /form-group -->
		<%= submit_tag("Submit", class: "btn btn-default submit") %>
	<% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% if @articles.exists? %>
      <% if signed_in? %>
        <%= link_to 'New Article', new_article_path %>
      <% end %>
      <% @articles.each do |article| %>
        <%= render article %>
      <% end %>
    <% else %>
      <p>There&rsquo;s nothing here! <%= link_to 'Get writing!', new_article_path %></p>
    <% end %>
    <%= will_paginate @articles, class: 'apple_pagination' %>
  </div><!-- /col -->
</div><!-- /row -->

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% if signed_in? && current_user.admin? %>
      <%= link_to 'New Article', new_article_path %>
    <% end %>
    <%= render @article %>
    <%= render 'new_comment' %>
    <%= render 'comments' %>
    <%= will_paginate @comments, class: 'apple_pagination' %>
  </div><!-- /col -->
</div><!-- /row -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div><!-- end navbar-header -->
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= 'active' if current_page?(portfolio_path) %>"><%= link_to "Portfolio", portfolio_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contact", contact_path %></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
        </li>
      </ul>
    </div><!-- end navbar-collapse -->
  </div><!--end nav container-fluid -->
</nav><!-- end navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cfblog</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% if notice %>
        <div class="alert alert-success" id="notice"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" id="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div><!-- /container-fluid -->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <article>
      <h2>About</h2>
      <div class="artbody">
        <p>Find me in app/views/static_pages/about.html.erb</p>

        <p>Images courtesy of:</p>

        <ul>
          <li><a href="https://www.toptal.com/designers/subtlepatterns/cross-stripes/">Cross Stripes</a> background pattern by <a href="http://www.facebook.com/stefanaleksic88">Stefan Aleksić</a>.</li>
        </ul>
      </div>
    </article>
  </div><!-- /col -->
</div><!-- /row -->

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
    <div class="contact-form">
      <%= form_tag("/static_pages/thank_you") do %>
        <%= flash[:notice] %>
        <div class="form-group">
          <%= label_tag :name, "Name:" %>
          <%= text_field_tag :name, nil, class: "form-control", placeholder: "Your Name", :required => true %>
        </div><!-- /form-group -->
        <div class="form-group">
          <%= label_tag :email, "Email:" %>
          <%= email_field_tag :email, nil, class: "form-control", placeholder: "Your Email Address", :required => true %>
        </div><!-- /form-group -->
        <div class="form-group">
          <%= label_tag :message, "Message:" %>
          <%= text_area_tag :message, nil, class: "form-control", placeholder: "Your Message" , :required => true %>
        </div><!-- /form-group -->
        <%= submit_tag "Send Message", class: 'btn btn-lg btn-primary btn-block' %>
      <% end %>
    </div><!-- /contact-form -->
  </div><!-- /col -->
</div><!-- /row -->

app/views/static_pages/portfolio.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <article>
      <h2>Portfolio</h2>
      <div class="artbody">
        <p>Find me in app/views/static_pages/portfolio.html.erb</p>
      </div>
    </article>
  </div><!-- /col -->
</div><!-- /row -->

app/views/static_pages/thank_you.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
    <h1>Thanks!</h1>
    <p>Thank you for taking the time to write. I&rsquo;ll get back to you as soon as I can.</p>
  </div><!-- /col-md-4 -->
</div><!-- /row -->

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>